apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: custom-pod-failure-experiment
  namespace: chaos-mesh 
spec:
  action: pod-kill
  mode: all 
  selector:
    namespaces:
      - chaos-experiment 
    labelSelectors:
      'app': 'react-app'
  duration: '30s'
  gracePeriod: 10 