apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: custom-time-shift-example-experiment
  namespace: chaos-mesh
spec:
  mode: all
  selector:
    namespaces:
      - chaos-experiment
    labelSelectors:
      app: react-app
  timeOffset: '-10m100ns'